import Link from "next/link";

import { updateAlertWorkflow } from "@/features/alerts/actions";
import { getAlertDetail } from "@/features/alerts/server";
import { formatKuwaitDateTime } from "@/lib/datetime/kuwait";

export default async function AlertDetailPage({ params, searchParams }: { params: Promise<{ alertId: string }>; searchParams: Promise<{ updated?: string; error?: string }> }) {
  const [{ alertId }, notice] = await Promise.all([params, searchParams]);
  const detail = await getAlertDetail(alertId);
  return <div className="grid gap-6"><header><p className="text-xs font-semibold uppercase tracking-wide text-brand">{detail.alert.alert_type.replaceAll("_", " ")}</p><h1 className="mt-2 text-2xl font-bold tracking-tight text-foreground">Alert · {detail.alert.status}</h1><p className="mt-2 text-muted">{detail.location?.name_en} · {formatKuwaitDateTime(detail.alert.created_at)}</p></header>{notice.updated ? <p className="rounded-xl bg-emerald-50 p-4 text-emerald-800">Alert updated and audited.</p> : null}{notice.error ? <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">The alert could not be updated.</p> : null}<section className="grid gap-4 rounded-xl border border-border bg-white p-6 sm:grid-cols-3"><div><p className="text-sm text-muted">Survey</p><p className="mt-1 font-bold">{detail.survey?.title_en ?? "System"}</p></div><div><p className="text-sm text-muted">Rating / threshold</p><p className="mt-1 font-bold">{detail.alert.rating_value ?? "—"} / {detail.alert.threshold_value ?? "—"}</p></div><div><p className="text-sm text-muted">Assigned</p><p className="mt-1 font-bold">{detail.profiles.find((row) => row.id === detail.alert.assigned_to)?.display_name ?? "Unassigned"}</p></div>{detail.alert.message ? <p className="sm:col-span-3">{detail.alert.message}</p> : null}{detail.alert.resolution_note ? <p className="sm:col-span-3 rounded-xl bg-background p-3">Internal resolution: {detail.alert.resolution_note}</p> : null}</section>{detail.response ? <Link className="font-semibold text-brand" href={`/dashboard/responses/${detail.response.id}`}>View related response →</Link> : null}
    {detail.canManage ? <form action={updateAlertWorkflow} className="grid gap-4 rounded-xl border border-border bg-white p-6 sm:grid-cols-2"><input type="hidden" name="alertId" value={alertId} /><label className="grid gap-2 text-sm font-semibold">Status<select name="status" defaultValue={detail.alert.status} className="rounded-lg border border-border px-3 py-2"><option value="open">Open / reopen</option><option value="acknowledged">Acknowledged</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select></label><label className="grid gap-2 text-sm font-semibold">Assign to<select name="assignedTo" defaultValue={detail.alert.assigned_to ?? ""} className="rounded-lg border border-border px-3 py-2"><option value="">Unassigned</option>{detail.profiles.map((row) => <option key={row.id} value={row.id}>{row.display_name}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold sm:col-span-2">Internal resolution note<textarea name="resolutionNote" maxLength={1000} defaultValue={detail.alert.resolution_note ?? ""} className="min-h-28 rounded-lg border border-border p-3" /></label><button className="justify-self-start rounded-lg bg-brand px-5 py-3 font-semibold text-white">Save alert workflow</button></form> : <p className="rounded-xl bg-background p-4 text-sm text-muted">Your role has read-only alert access.</p>}
  </div>;
}
