import { updateProfile } from "@/features/account/actions";
import { getAccountSettings } from "@/features/account/server";
import { getMessages } from "@/lib/i18n/messages";

export default async function AccountProfilePage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const [result, notice] = await Promise.all([getAccountSettings(), searchParams]);
  const messages = getMessages(result.context.profile.locale);
  return <div className="grid gap-6"><h1 className="text-2xl font-bold tracking-tight text-foreground">{messages["account.profile"]}</h1>{notice.updated ? <p className="rounded-xl bg-emerald-50 p-4">{messages["common.save"]}</p> : null}<form action={updateProfile} className="grid max-w-2xl gap-4 rounded-xl border border-border bg-white p-6"><label className="grid gap-2 font-semibold">{messages["account.displayName"]}<input name="displayName" required maxLength={120} defaultValue={result.context.profile.displayName} className="rounded-lg border border-border px-4 py-3" /></label><label className="grid gap-2 font-semibold">{messages["settings.language"]}<select name="locale" defaultValue={result.context.profile.locale} className="rounded-lg border border-border px-4 py-3"><option value="en">English</option><option value="ar">العربية</option></select></label><button className="justify-self-start rounded-lg bg-brand px-5 py-3 font-semibold text-white">{messages["common.save"]}</button></form><section className="grid gap-3"><h2 className="text-base font-semibold text-foreground">{messages["account.memberships"]}</h2>{result.memberships.map((membership) => { const organization = Array.isArray(membership.organizations) ? membership.organizations[0] : membership.organizations; return <article key={membership.id} className="rounded-xl border border-border bg-white p-5"><p className="font-bold">{result.context.profile.locale === "ar" ? organization?.name_ar : organization?.name_en}</p><p className="mt-1 text-sm text-muted">{membership.role.replaceAll("_", " ")} · {membership.status}</p></article>; })}{!result.memberships.length ? <p className="text-muted">{messages["common.empty"]}</p> : null}</section></div>;
}
