import "server-only";

import { parseServerEnv } from "./schema";

export function getServerEnv() {
  return parseServerEnv({
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NODE_ENV: process.env.NODE_ENV,
    APP_ENV: process.env.APP_ENV,
    SUPABASE_PROJECT_ENVIRONMENT: process.env.SUPABASE_PROJECT_ENVIRONMENT,
    SUPABASE_PROJECT_REF: process.env.SUPABASE_PROJECT_REF,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    SUBMISSION_FINGERPRINT_SECRET: process.env.SUBMISSION_FINGERPRINT_SECRET,
    APP_TIME_ZONE: process.env.APP_TIME_ZONE,
    EMAIL_DELIVERY_MODE: process.env.EMAIL_DELIVERY_MODE,
    SMTP_HOST: process.env.SMTP_HOST,
    SMTP_PORT: process.env.SMTP_PORT,
    SMTP_SECURE: process.env.SMTP_SECURE,
    SMTP_USERNAME: process.env.SMTP_USERNAME,
    SMTP_PASSWORD: process.env.SMTP_PASSWORD,
    SMTP_FROM_EMAIL: process.env.SMTP_FROM_EMAIL,
    SMTP_FROM_NAME: process.env.SMTP_FROM_NAME,
    BOT_PROTECTION_PROVIDER: process.env.BOT_PROTECTION_PROVIDER,
    BOT_PROTECTION_SITE_KEY: process.env.BOT_PROTECTION_SITE_KEY,
    BOT_PROTECTION_SECRET_KEY: process.env.BOT_PROTECTION_SECRET_KEY,
    BOT_PROTECTION_EXPECTED_HOSTNAME: process.env.BOT_PROTECTION_EXPECTED_HOSTNAME,
    BOT_PROTECTION_EXPECTED_ACTION: process.env.BOT_PROTECTION_EXPECTED_ACTION,
    BOT_PROTECTION_LOCAL_BYPASS: process.env.BOT_PROTECTION_LOCAL_BYPASS,
    LOG_LEVEL: process.env.LOG_LEVEL,
    DEPLOYMENT_VERSION: process.env.DEPLOYMENT_VERSION,
    VERCEL_ENV: process.env.VERCEL_ENV,
    VERCEL_GIT_COMMIT_SHA: process.env.VERCEL_GIT_COMMIT_SHA,
  });
}
