import { updateOrganizationSettings } from "@/features/settings/actions";
import { getOrganizationSettings } from "@/features/settings/server";
import { getMessages } from "@/lib/i18n/messages";

export default async function OrganizationSettingsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const notice = await searchParams;
  const { context, organization: o } = await getOrganizationSettings();
  const m = getMessages(context.profile.locale);
  const input = "rounded-lg border border-border px-3 py-2";
  return <div className="grid gap-6"><h1 className="text-2xl font-bold tracking-tight text-foreground">{m["settings.organization"]}</h1>{notice.updated ? <p className="rounded-xl bg-emerald-50 p-4">Settings updated and audited.</p> : null}{notice.error ? <p role="alert" className="rounded-xl bg-red-50 p-4">{m["common.error"]}</p> : null}<form action={updateOrganizationSettings} className="grid gap-4 rounded-xl border border-border bg-white p-6 md:grid-cols-2"><Field label={m["settings.nameEn"]} name="nameEn" value={o.name_en} className={input} required /><Field label={m["settings.nameAr"]} name="nameAr" value={o.name_ar} className={input} dir="rtl" /><Field label={m["settings.slug"]} name="slug" value={o.slug} className={input} required /><Field label={m["settings.category"]} name="businessCategory" value={o.business_category} className={input} required /><Field label={m["settings.phone"]} name="phone" value={o.phone ?? ""} className={input} /><Field label={m["auth.email"]} name="email" type="email" value={o.email ?? ""} className={input} /><Field label={m["settings.website"]} name="website" type="url" value={o.website ?? ""} className={input} /><Field label="Support email" name="supportEmail" type="email" value={o.support_email ?? ""} className={input} /><Field label="Support phone" name="supportPhone" value={o.support_phone ?? ""} className={input} /><label className="grid gap-2 font-semibold">{m["settings.language"]}<select name="defaultLocale" defaultValue={o.default_locale} className={input}><option value="en">English</option><option value="ar">العربية</option></select></label><label className="grid gap-2 font-semibold">Date format<select name="dateFormat" defaultValue={o.date_format} className={input}><option>dd/MM/yyyy</option><option>yyyy-MM-dd</option></select></label><label className="grid gap-2 font-semibold">Number format<select name="numberFormat" defaultValue={o.number_format} className={input}><option>en-KW</option><option>ar-KW</option></select></label><label className="grid gap-2 font-semibold md:col-span-2">Description (English)<textarea name="descriptionEn" defaultValue={o.description_en ?? ""} maxLength={2000} className={`${input} min-h-28`} /></label><label className="grid gap-2 font-semibold md:col-span-2">الوصف بالعربية<textarea name="descriptionAr" dir="rtl" defaultValue={o.description_ar ?? ""} maxLength={2000} className={`${input} min-h-28`} /></label><button className="justify-self-start rounded-lg bg-brand px-5 py-3 font-semibold text-white">{m["settings.save"]}</button></form><p className="text-sm text-muted">Changing the organization slug requires a sign-in within the last 30 minutes.</p></div>;
}

function Field({ label, ...props }: { label: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <label className="grid gap-2 font-semibold">{label}<input {...props} /></label>; }
