import Link from "next/link";

import { EmptyState } from "@/components/dashboard/empty-state";
import { listResponses } from "@/features/responses/server";
import { formatKuwaitDateTime } from "@/lib/datetime/kuwait";

type Filters = { q?: string; survey?: string; location?: string; rating?: string; workflow?: string; tag?: string; assignee?: string; alert?: string; unresolved?: string; page?: string };

export default async function ResponsesPage({ searchParams }: { searchParams: Promise<Filters> }) {
  const filters = await searchParams;
  const result = await listResponses(filters);
  const query = new URLSearchParams(Object.entries(filters).filter((entry): entry is [string, string] => Boolean(entry[1]))).toString();
  const control = "rounded-xl border border-border px-3 py-2";
  return <div className="grid gap-7"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-brand">Internal response workflow</p><h1 className="mt-2 text-3xl font-bold">Responses</h1></div><div className="flex flex-wrap gap-2"><a className="rounded-xl border border-border bg-white px-4 py-2 font-bold" href={`/api/exports/responses?${query}`}>Responses CSV</a><a className="rounded-xl border border-border bg-white px-4 py-2 font-bold" href={`/api/exports/response_answers?${query}`}>Answers CSV</a></div></header><form className="grid gap-3 rounded-2xl border border-border bg-white p-4 sm:grid-cols-3 xl:grid-cols-5"><input name="q" defaultValue={filters.q} placeholder="Survey or location" className={control} /><select name="survey" defaultValue={filters.survey ?? ""} className={control}><option value="">All surveys</option>{result.surveys.map((survey) => <option key={survey.id} value={survey.id}>{survey.title_en}</option>)}</select><select name="location" defaultValue={filters.location ?? ""} className={control}><option value="">All locations</option>{result.locations.map((location) => <option key={location.id} value={location.id}>{location.name_en}</option>)}</select><select name="rating" defaultValue={filters.rating ?? ""} className={control}><option value="">All ratings</option>{[0,1,2,3,4,5,6,7,8,9,10].map((rating) => <option key={rating}>{rating}</option>)}</select><select name="workflow" defaultValue={filters.workflow ?? ""} className={control}><option value="">All workflows</option><option value="unread">Unread</option><option value="reviewed">Reviewed</option><option value="action_required">Action required</option><option value="resolved">Resolved</option></select><input name="tag" defaultValue={filters.tag} placeholder="Internal tag" className={control} /><select name="assignee" defaultValue={filters.assignee ?? ""} className={control}><option value="">Any assignee</option>{result.profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.display_name}</option>)}</select><select name="alert" defaultValue={filters.alert ?? ""} className={control}><option value="">Any alert</option><option value="open">Open alert</option><option value="acknowledged">Acknowledged</option><option value="resolved">Resolved alert</option><option value="dismissed">Dismissed</option></select><label className="flex items-center gap-2 rounded-xl border border-border px-3"><input type="checkbox" name="unresolved" value="1" defaultChecked={filters.unresolved === "1"} /> Unresolved only</label><button className="rounded-xl bg-brand px-4 py-2 font-semibold text-white">Filter</button></form>
    {result.rows.length === 0 ? <EmptyState title="No matching responses" description="Responses appear here after customers submit published surveys at permitted locations." /> : <div className="overflow-x-auto rounded-2xl border border-border bg-white"><table className="w-full min-w-[900px] text-sm"><thead className="bg-background text-muted"><tr><th className="p-4 text-start">Submitted</th><th className="p-4 text-start">Survey</th><th className="p-4 text-start">Location</th><th className="p-4 text-start">Rating</th><th className="p-4 text-start">Workflow</th><th className="p-4 text-start">Tags</th><th className="p-4 text-start">Alert</th></tr></thead><tbody>{result.rows.map((row) => <tr key={row.id} className="border-t border-border"><td className="p-4"><Link className="font-semibold text-brand hover:underline" href={`/dashboard/responses/${row.id}`}>{formatKuwaitDateTime(row.submitted_at)}</Link></td><td className="p-4">{row.survey?.title_en}</td><td className="p-4">{row.location?.name_en}</td><td className="p-4">{row.overall_rating ?? "—"}</td><td className="p-4">{row.workflow_status.replaceAll("_", " ")}</td><td className="p-4">{row.internal_tags.join(", ") || "—"}</td><td className="p-4">{row.alert?.alert_type === "low_score" ? <span className="rounded-full bg-red-50 px-2 py-1 font-semibold text-red-700">Low score · {row.alert.status}</span> : "—"}</td></tr>)}</tbody></table></div>}
    {result.pageCount > 1 ? <nav aria-label="Response pages" className="flex justify-center gap-2">{Array.from({ length: result.pageCount }, (_, index) => index + 1).map((page) => <Link key={page} className={`rounded-lg border px-3 py-2 ${page === result.page ? "border-brand text-brand" : "border-border"}`} href={{ pathname: "/dashboard/responses", query: { ...filters, page } }}>{page}</Link>)}</nav> : null}
  </div>;
}
