import Link from "next/link";

import { EmptyState } from "@/components/dashboard/empty-state";
import { listResponses } from "@/features/responses/server";
import { formatKuwaitDateTime } from "@/lib/datetime/kuwait";

export default async function ResponsesPage({ searchParams }: { searchParams: Promise<{ q?: string; survey?: string; location?: string; rating?: string; page?: string }> }) {
  const filters = await searchParams;
  const result = await listResponses(filters);
  return <div className="grid gap-7"><header><p className="text-sm font-bold text-brand">Read-only inbox</p><h1 className="mt-2 text-3xl font-bold">Responses</h1></header><form className="grid gap-3 rounded-2xl border border-border bg-white p-4 sm:grid-cols-5"><input name="q" defaultValue={filters.q} placeholder="Survey or location" className="rounded-xl border border-border px-3 py-2" /><select name="survey" defaultValue={filters.survey ?? ""} className="rounded-xl border border-border px-3 py-2"><option value="">All surveys</option>{result.surveys.map((survey) => <option key={survey.id} value={survey.id}>{survey.title_en}</option>)}</select><select name="location" defaultValue={filters.location ?? ""} className="rounded-xl border border-border px-3 py-2"><option value="">All locations</option>{result.locations.map((location) => <option key={location.id} value={location.id}>{location.name_en}</option>)}</select><select name="rating" defaultValue={filters.rating ?? ""} className="rounded-xl border border-border px-3 py-2"><option value="">All ratings</option>{[0,1,2,3,4,5,6,7,8,9,10].map((rating) => <option key={rating}>{rating}</option>)}</select><button className="rounded-xl border border-border px-4 py-2 font-semibold">Filter</button></form>
    {result.rows.length === 0 ? <EmptyState title="No matching responses" description="Responses appear here after customers submit published surveys at permitted locations." /> : <div className="overflow-x-auto rounded-2xl border border-border bg-white"><table className="w-full min-w-[760px] text-sm"><thead className="bg-background text-muted"><tr><th className="p-4 text-start">Submitted</th><th className="p-4 text-start">Survey</th><th className="p-4 text-start">Location</th><th className="p-4 text-start">Rating</th><th className="p-4 text-start">Alert</th></tr></thead><tbody>{result.rows.map((row) => <tr key={row.id} className="border-t border-border"><td className="p-4"><Link className="font-semibold text-brand hover:underline" href={`/dashboard/responses/${row.id}`}>{formatKuwaitDateTime(row.submitted_at)}</Link></td><td className="p-4">{row.survey?.title_en}</td><td className="p-4">{row.location?.name_en}</td><td className="p-4">{row.overall_rating ?? "—"}</td><td className="p-4">{row.alert?.alert_type === "low_score" ? <span className="rounded-full bg-red-50 px-2 py-1 font-semibold text-red-700">Low score · {row.alert.status}</span> : "—"}</td></tr>)}</tbody></table></div>}
    {result.pageCount > 1 ? <nav aria-label="Response pages" className="flex justify-center gap-2">{Array.from({ length: result.pageCount }, (_, index) => index + 1).map((page) => <Link key={page} className={`rounded-lg border px-3 py-2 ${page === result.page ? "border-brand text-brand" : "border-border"}`} href={{ pathname: "/dashboard/responses", query: { ...filters, page } }}>{page}</Link>)}</nav> : null}
  </div>;
}
