import { removeMember, transferOwnership, updateMember } from "@/features/team/actions";
import { getMember } from "@/features/team/server";
import { getMessages } from "@/lib/i18n/messages";

export default async function MemberPage({ params, searchParams }: { params: Promise<{ memberId: string }>; searchParams: Promise<Record<string, string | undefined>> }) {
  const [{ memberId }, notice] = await Promise.all([params, searchParams]);
  const result = await getMember(memberId);
  const messages = getMessages(result.context.profile.locale);
  const role = result.context.profile.platformRole ?? result.context.membership?.role;
  const canManage = ["platform_admin", "organization_owner", "organization_admin"].includes(role ?? "") && result.member.user_id !== result.context.user.id && result.member.role !== "organization_owner";
  return <div className="grid gap-6"><header><p className="text-xs font-semibold uppercase tracking-wide text-brand">{result.member.email}</p><h1 className="mt-2 text-2xl font-bold tracking-tight text-foreground">{result.member.display_name}</h1></header>{notice.updated ? <p className="rounded-xl bg-emerald-50 p-4">Member updated and audited.</p> : null}{notice.error ? <p role="alert" className="rounded-xl bg-red-50 p-4">{messages["common.error"]}</p> : null}
    <section className="rounded-xl border border-border bg-white p-6"><p>{result.member.role.replaceAll("_", " ")} · {result.member.status}</p><p className="mt-2 text-sm text-muted">{result.member.locations.map((location) => result.context.profile.locale === "ar" ? location.name_ar : location.name_en).join(", ") || "All organization locations"}</p></section>
    {canManage ? <form action={updateMember} className="grid gap-4 rounded-xl border border-border bg-white p-6 md:grid-cols-2"><input type="hidden" name="membershipId" value={result.member.id} /><label className="grid gap-2 font-semibold">{messages["team.role"]}<select name="role" defaultValue={result.member.role} className="rounded-lg border border-border px-3 py-2"><option value="organization_admin">Organization admin</option><option value="location_manager">Location manager</option><option value="analyst">Analyst</option></select></label><label className="grid gap-2 font-semibold">{messages["team.status"]}<select name="status" defaultValue={result.member.status} className="rounded-lg border border-border px-3 py-2"><option value="active">Active</option><option value="archived">Inactive</option></select></label><fieldset className="grid gap-2 rounded-xl border border-border p-4 md:col-span-2"><legend className="px-2 font-semibold">{messages["team.locations"]}</legend>{result.locations.map((location) => <label key={location.id} className="flex gap-2"><input type="checkbox" name="locations" value={location.id} defaultChecked={result.member.locations.some((item) => item.id === location.id)} />{result.context.profile.locale === "ar" ? location.name_ar : location.name_en}</label>)}</fieldset><button className="justify-self-start rounded-lg bg-brand px-5 py-3 font-semibold text-white">{messages["team.save"]}</button></form> : <p className="rounded-xl bg-background p-4 text-muted">Read-only access</p>}
    {canManage ? <div className="flex flex-wrap gap-3"><form action={removeMember}><input type="hidden" name="membershipId" value={result.member.id} /><button className="rounded-lg border border-red-200 px-4 py-2 font-medium text-red-700">{messages["team.remove"]}</button></form>{role === "organization_owner" ? <form action={transferOwnership}><input type="hidden" name="membershipId" value={result.member.id} /><button className="rounded-lg border border-amber-300 px-4 py-2 font-medium text-amber-800">{messages["team.transfer"]}</button></form> : null}</div> : null}
  </div>;
}
