import { updateBranding } from "@/features/settings/actions";
import { getOrganizationSettings } from "@/features/settings/server";
import { getMessages } from "@/lib/i18n/messages";

export default async function BrandingPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const notice = await searchParams;
  const { context, organization: o } = await getOrganizationSettings();
  const m = getMessages(context.profile.locale);
  const control = "rounded-xl border border-border px-3 py-2";
  return <div className="grid gap-7"><h1 className="text-3xl font-bold">{m["branding.title"]}</h1>{notice.updated ? <p className="rounded-xl bg-emerald-50 p-4">Branding updated.</p> : null}{notice.error ? <p role="alert" className="rounded-xl bg-red-50 p-4">{m["validation.fileType"]} {m["validation.fileSize"]}</p> : null}<form action={updateBranding} className="grid gap-4 rounded-3xl border border-border bg-white p-6 md:grid-cols-2" encType="multipart/form-data"><label className="grid gap-2 font-semibold">{m["branding.primary"]}<input name="primaryColor" type="color" defaultValue={o.primary_color} className="h-12 w-full" /></label><label className="grid gap-2 font-semibold">{m["branding.accent"]}<input name="accentColor" type="color" defaultValue={o.accent_color} className="h-12 w-full" /></label><LogoField label={m["branding.logo"]} name="logo" /><LogoField label={m["branding.icon"]} name="iconLogo" /><LogoField label={m["branding.darkLogo"]} name="darkLogo" /><label className="grid gap-2 font-semibold">Header style<select name="headerStyle" defaultValue={o.survey_header_style} className={control}><option value="standard">Standard</option><option value="compact">Compact</option><option value="centered">Centered</option></select></label><Text label="Thank-you (English)" name="thankYouEn" value={o.default_thank_you_en ?? ""} className={control} /><Text label="رسالة الشكر" name="thankYouAr" value={o.default_thank_you_ar ?? ""} className={control} dir="rtl" /><Text label="Footer (English)" name="footerEn" value={o.footer_text_en ?? ""} className={control} /><Text label="نص التذييل" name="footerAr" value={o.footer_text_ar ?? ""} className={control} dir="rtl" /><button className="justify-self-start rounded-xl bg-brand px-5 py-3 font-bold text-white">{m["common.save"]}</button></form><p className="text-sm text-muted">PNG, JPEG, or WebP only; verified by file content; maximum 2 MB. SVG is not accepted.</p></div>;
}
function LogoField({ label, name }: { label: string; name: string }) { return <label className="grid gap-2 font-semibold">{label}<input type="file" name={name} accept="image/png,image/jpeg,image/webp" className="rounded-xl border border-border p-3" /></label>; }
function Text({ label, name, value, ...props }: { label: string; name: string; value: string } & React.TextareaHTMLAttributes<HTMLTextAreaElement>) { return <label className="grid gap-2 font-semibold">{label}<textarea {...props} name={name} defaultValue={value} maxLength={500} /></label>; }
