import Link from "next/link";

import { listAlerts } from "@/features/alerts/server";
import { formatKuwaitDateTime } from "@/lib/datetime/kuwait";

export default async function AlertsPage({ searchParams }: { searchParams: Promise<{ status?: string; location?: string; assigned?: string; page?: string }> }) {
  const filters = await searchParams;
  const result = await listAlerts(filters);
  return <div className="grid gap-7"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-brand">Operational workflow</p><h1 className="mt-2 text-3xl font-bold">Alerts</h1></div><Link href={{ pathname: "/api/exports/alert_reports", query: { alertStatus: filters.status, location: filters.location, assignee: filters.assigned } }} className="rounded-xl border border-border bg-white px-4 py-2 font-bold">Export alerts CSV</Link></header><form className="grid gap-3 rounded-2xl border border-border bg-white p-4 sm:grid-cols-4"><select name="status" defaultValue={filters.status ?? ""} className="rounded-xl border border-border px-3 py-2"><option value="">All statuses</option><option value="open">Open</option><option value="acknowledged">Acknowledged</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select><select name="location" defaultValue={filters.location ?? ""} className="rounded-xl border border-border px-3 py-2"><option value="">All locations</option>{result.locations.map((row) => <option key={row.id} value={row.id}>{row.name_en}</option>)}</select><select name="assigned" defaultValue={filters.assigned ?? ""} className="rounded-xl border border-border px-3 py-2"><option value="">Any assignee</option>{result.profiles.map((row) => <option key={row.id} value={row.id}>{row.display_name}</option>)}</select><button className="rounded-xl bg-brand px-4 py-2 font-bold text-white">Filter</button></form>
    <div className="overflow-x-auto rounded-2xl border border-border bg-white"><table className="w-full min-w-[800px] text-sm"><thead className="bg-background text-muted"><tr><th className="p-4 text-start">Created</th><th className="p-4 text-start">Status</th><th className="p-4 text-start">Survey</th><th className="p-4 text-start">Location</th><th className="p-4 text-start">Trigger</th><th className="p-4 text-start">Assignee</th></tr></thead><tbody>{result.rows.map((alert) => <tr key={alert.id} className="border-t border-border"><td className="p-4"><Link className="font-semibold text-brand" href={`/dashboard/alerts/${alert.id}`}>{formatKuwaitDateTime(alert.created_at)}</Link></td><td className="p-4">{alert.status}</td><td className="p-4">{alert.survey?.title_en ?? "System"}</td><td className="p-4">{alert.location?.name_en}</td><td className="p-4">{alert.alert_type} {alert.rating_value === null ? "" : `· ${alert.rating_value}`}</td><td className="p-4">{alert.assignee?.display_name ?? "Unassigned"}</td></tr>)}</tbody></table>{result.rows.length === 0 ? <p className="p-8 text-center text-muted">No alerts match these filters.</p> : null}</div>
    {result.pageCount > 1 ? <nav aria-label="Alert pages" className="flex justify-center gap-2">{Array.from({ length: result.pageCount }, (_, i) => i + 1).map((page) => <Link key={page} className="rounded-lg border border-border px-3 py-2" href={{ pathname: "/dashboard/alerts", query: { ...filters, page } }}>{page}</Link>)}</nav> : null}
  </div>;
}
