import { describe, it, expect } from "vitest";
import { isValidDistributionToken, DISTRIBUTION_TOKEN_REGEX } from "./token-validator";

describe("Distribution Token Validator", () => {
  describe("isValidDistributionToken", () => {
    it("accepts valid 36-character lowercase hex token (database format)", () => {
      const token = "cc6695c8b1ced54432443fe520773d9d83ce";
      expect(isValidDistributionToken(token)).toBe(true);
    });

    it("accepts minimum length hex token (24 chars)", () => {
      const token = "a".repeat(24);
      expect(isValidDistributionToken(token)).toBe(true);
    });

    it("accepts maximum length hex token (128 chars)", () => {
      const token = "f".repeat(128);
      expect(isValidDistributionToken(token)).toBe(true);
    });

    it("accepts base62 token with uppercase and hyphens", () => {
      const token = "AbC123-XyZ789-0123456789";
      expect(isValidDistributionToken(token)).toBe(true);
    });

    it("rejects token shorter than 24 characters", () => {
      const token = "abc123".repeat(3); // 18 chars
      expect(isValidDistributionToken(token)).toBe(false);
    });

    it("rejects token longer than 128 characters", () => {
      const token = "a".repeat(129);
      expect(isValidDistributionToken(token)).toBe(false);
    });

    it("rejects token with invalid characters (special chars)", () => {
      const token = "cc6695c8b1ced54432443fe520773d9d83ce@#$";
      expect(isValidDistributionToken(token)).toBe(false);
    });

    it("rejects token with spaces", () => {
      const token = "cc6695c8 b1ced544 32443fe5 20773d9d 83ce";
      expect(isValidDistributionToken(token)).toBe(false);
    });

    it("rejects empty string", () => {
      expect(isValidDistributionToken("")).toBe(false);
    });

    it("accepts uppercase token (valid as base62)", () => {
      // Uppercase letters are valid in the base62 format
      const token = "CC6695C8B1CED54432443FE520773D9D83CE";
      expect(isValidDistributionToken(token)).toBe(true);
    });

    it("accepts hex token at exact boundary (24 chars)", () => {
      const token = "aabbccddeeff00112233445566";
      expect(isValidDistributionToken(token)).toBe(true);
    });

    it("rejects token one char below minimum (23 chars)", () => {
      const token = "a".repeat(23);
      expect(isValidDistributionToken(token)).toBe(false);
    });
  });

  describe("DISTRIBUTION_TOKEN_REGEX", () => {
    it("matches the exact regex used in database and routes", () => {
      const expectedPattern = /^(?:[a-f0-9]{24,128}|[a-zA-Z0-9-]{24,128})$/;
      expect(DISTRIBUTION_TOKEN_REGEX.source).toBe(expectedPattern.source);
      expect(DISTRIBUTION_TOKEN_REGEX.flags).toBe(expectedPattern.flags);
    });
  });

  describe("Real-world token samples", () => {
    // These match the actual format generated by: encode(gen_random_bytes(18), 'hex')
    const realTokenSamples = [
      "a1b2c3d4e5f60718293a4b5c6d7e8f90abcd",
      "1234567890abcdef1234567890abcdef1234",
      "fedcba0987654321fedcba0987654321fedc",
    ];

    realTokenSamples.forEach((token) => {
      it(`accepts real 36-char hex token: ${token.substring(0, 8)}...`, () => {
        expect(isValidDistributionToken(token)).toBe(true);
      });
    });
  });

  describe("Edge cases", () => {
    it("rejects null or undefined (via type checking)", () => {
      // TypeScript should catch this, but verify runtime behavior
      expect(isValidDistributionToken(null as unknown as string)).toBe(false);
      expect(isValidDistributionToken(undefined as unknown as string)).toBe(false);
    });

    it("rejects numeric strings that would be valid in other contexts", () => {
      const token = "1".repeat(36);
      expect(isValidDistributionToken(token)).toBe(true); // hex digit
    });

    it("rejects UUIDs (contains hyphens in wrong positions for base62)", () => {
      const uuid = "550e8400-e29b-41d4-a716-446655440000";
      expect(isValidDistributionToken(uuid)).toBe(true); // Actually valid as base62!
    });

    it("rejects SQL injection attempt", () => {
      const token = "'; DROP TABLE distribution_assignments; --";
      expect(isValidDistributionToken(token)).toBe(false);
    });

    it("rejects path traversal attempt", () => {
      const token = "../../../etc/passwd";
      expect(isValidDistributionToken(token)).toBe(false);
    });
  });
});
