import Link from "next/link";

import { listTeam } from "@/features/team/server";
import { formatKuwaitDateTime } from "@/lib/datetime/kuwait";
import { getMessages } from "@/lib/i18n/messages";

export default async function TeamPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const raw = await searchParams;
  const result = await listTeam(raw);
  const messages = getMessages(result.context.profile.locale);
  const canManage = result.context.profile.platformRole === "platform_admin" || ["organization_owner", "organization_admin"].includes(result.context.membership?.role ?? "");
  return <div className="grid gap-7"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-brand">{messages["team.members"]}</p><h1 className="mt-2 text-3xl font-bold">{messages["team.title"]}</h1></div>{canManage ? <Link href="/dashboard/team/invitations" className="rounded-xl bg-brand px-4 py-2 font-bold text-white">{messages["team.invitations"]}</Link> : null}</header>
    <form className="grid gap-3 rounded-2xl border border-border bg-white p-4 md:grid-cols-4"><input name="q" defaultValue={raw.q} placeholder={messages["team.search"]} className="rounded-xl border border-border px-3 py-2" /><select name="role" defaultValue={raw.role ?? ""} className="rounded-xl border border-border px-3 py-2"><option value="">{messages["team.role"]}</option><option value="organization_admin">Organization admin</option><option value="location_manager">Location manager</option><option value="analyst">Analyst</option></select><select name="location" defaultValue={raw.location ?? ""} className="rounded-xl border border-border px-3 py-2"><option value="">{messages["team.locations"]}</option>{result.locations.map((location) => <option key={location.id} value={location.id}>{result.context.profile.locale === "ar" ? location.name_ar : location.name_en}</option>)}</select><button className="rounded-xl bg-brand px-4 py-2 font-bold text-white">{messages["common.filter"]}</button></form>
    <div className="overflow-x-auto rounded-2xl border border-border bg-white"><table className="w-full min-w-[950px] text-sm"><thead className="bg-background text-muted"><tr><th className="p-4 text-start">{messages["team.name"]}</th><th className="p-4 text-start">{messages["auth.email"]}</th><th className="p-4 text-start">{messages["team.role"]}</th><th className="p-4 text-start">{messages["team.locations"]}</th><th className="p-4 text-start">{messages["team.status"]}</th><th className="p-4 text-start">{messages["team.joined"]}</th><th className="p-4 text-start">{messages["team.activity"]}</th></tr></thead><tbody>{result.members.map((member) => <tr key={member.id} className="border-t border-border"><td className="p-4"><Link className="font-bold text-brand" href={`/dashboard/team/${member.id}`}>{member.display_name}</Link></td><td className="p-4">{member.email}</td><td className="p-4">{member.role.replaceAll("_", " ")}</td><td className="p-4">{member.locations.map((location) => result.context.profile.locale === "ar" ? location.name_ar : location.name_en).join(", ") || "—"}</td><td className="p-4">{member.status}</td><td className="p-4">{formatKuwaitDateTime(member.created_at, result.context.profile.locale)}</td><td className="p-4">{member.last_sign_in_at ? formatKuwaitDateTime(member.last_sign_in_at, result.context.profile.locale) : "—"}</td></tr>)}</tbody></table>{result.members.length === 0 ? <p className="p-8 text-center text-muted">{messages["common.empty"]}</p> : null}</div>
    {result.total > result.page_size ? <nav aria-label="Team pages" className="flex justify-center gap-2">{Array.from({ length: Math.ceil(result.total / result.page_size) }, (_, index) => index + 1).map((page) => <Link key={page} className="rounded-lg border border-border px-3 py-2" href={{ pathname: "/dashboard/team", query: { ...raw, page } }}>{page}</Link>)}</nav> : null}
  </div>;
}
