import { changeAccountPassword, deactivateAccount, signOutOtherSessions } from "@/features/account/actions";
import { getAccountSettings } from "@/features/account/server";
import { getMessages } from "@/lib/i18n/messages";

export default async function AccountSecurityPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const [result, notice] = await Promise.all([getAccountSettings(), searchParams]);
  const messages = getMessages(result.context.profile.locale);
  return <div className="grid max-w-3xl gap-7"><h1 className="text-3xl font-bold">{messages["account.security"]}</h1>{notice.error ? <p role="alert" className="rounded-xl bg-red-50 p-4">{notice.error === "ownership" ? "Transfer organization ownership before deactivating this account." : messages["common.error"]}</p> : null}<section className="rounded-3xl border border-border bg-white p-6"><h2 className="text-xl font-bold">{messages["account.changePassword"]}</h2><form action={changeAccountPassword} className="mt-5 grid gap-4"><input aria-label={messages["auth.password"]} name="password" type="password" minLength={12} required className="rounded-xl border border-border px-4 py-3" /><input aria-label="Confirm password" name="confirmPassword" type="password" minLength={12} required className="rounded-xl border border-border px-4 py-3" /><button className="justify-self-start rounded-xl bg-brand px-5 py-3 font-bold text-white">{messages["account.changePassword"]}</button></form></section><section className="rounded-3xl border border-border bg-white p-6"><h2 className="text-xl font-bold">{messages["account.signOutOthers"]}</h2><p className="mt-2 text-sm text-muted">Last verified sign-in: {result.user?.last_sign_in_at ? new Date(result.user.last_sign_in_at).toLocaleString(result.context.profile.locale === "ar" ? "ar-KW" : "en-KW", { timeZone: "Asia/Kuwait" }) : "—"}</p><form action={signOutOtherSessions} className="mt-4"><button className="rounded-xl border border-border px-4 py-2 font-bold">{messages["account.signOutOthers"]}</button></form></section><section className="rounded-3xl border border-red-200 bg-white p-6"><h2 className="text-xl font-bold text-red-800">{messages["account.deactivate"]}</h2><p className="mt-2 text-sm text-muted">Deactivation preserves audit and historical feedback records. Owners must transfer ownership first. Full deletion remains a reviewed support process.</p><form action={deactivateAccount} className="mt-4"><button className="rounded-xl bg-red-700 px-4 py-2 font-bold text-white">{messages["account.deactivate"]}</button></form></section></div>;
}
