import { createInvitation, resendInvitation, revokeInvitation } from "@/features/team/actions";
import { listInvitations } from "@/features/team/server";
import { formatKuwaitDateTime } from "@/lib/datetime/kuwait";
import { getMessages } from "@/lib/i18n/messages";

export default async function InvitationsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const notices = await searchParams;
  const result = await listInvitations();
  const messages = getMessages(result.context.profile.locale);
  return <div className="grid gap-6"><header><p className="text-xs font-semibold uppercase tracking-wide text-brand">{messages["team.invite"]}</p><h1 className="mt-2 text-2xl font-bold tracking-tight text-foreground">{messages["team.invitations"]}</h1></header>{notices.created || notices.resent || notices.revoked ? <p className="rounded-xl bg-emerald-50 p-4 text-emerald-800">Invitation workflow updated and audited.</p> : null}{notices.error ? <p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{messages["common.error"]}</p> : null}
    <form action={createInvitation} className="grid gap-4 rounded-xl border border-border bg-white p-6 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">{messages["auth.email"]}<input required name="email" type="email" maxLength={320} className="rounded-lg border border-border px-3 py-2" /></label><label className="grid gap-2 text-sm font-semibold">{messages["team.role"]}<select name="role" className="rounded-lg border border-border px-3 py-2"><option value="organization_admin">Organization admin</option><option value="location_manager">Location manager</option><option value="analyst">Analyst</option></select></label><fieldset className="grid gap-2 rounded-xl border border-border p-4 md:col-span-2"><legend className="px-2 font-semibold">{messages["team.locations"]}</legend>{result.locations.map((location) => <label key={location.id} className="flex gap-2"><input type="checkbox" name="locations" value={location.id} />{result.context.profile.locale === "ar" ? location.name_ar : location.name_en}</label>)}</fieldset><label className="grid gap-2 text-sm font-semibold">Language<select name="locale" className="rounded-lg border border-border px-3 py-2"><option value="en">English</option><option value="ar">العربية</option></select></label><label className="grid gap-2 text-sm font-semibold">{messages["team.expiration"]}<select name="expiresDays" className="rounded-lg border border-border px-3 py-2"><option value="1">1 day</option><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></select></label><label className="grid gap-2 text-sm font-semibold md:col-span-2">{messages["team.personalMessage"]}<textarea name="personalMessage" maxLength={500} className="min-h-24 rounded-lg border border-border p-3" /></label><button className="justify-self-start rounded-lg bg-brand px-5 py-3 font-semibold text-white">{messages["team.invite"]}</button></form>
    <section className="grid gap-3"><h2 className="text-base font-semibold text-foreground">{messages["team.invitations"]}</h2>{result.invitations.map((invitation) => <article key={invitation.id} className="grid gap-3 rounded-xl border border-border bg-white p-5 md:grid-cols-[1fr_auto]"><div><p className="font-bold">{invitation.email}</p><p className="text-sm text-muted">{invitation.role.replaceAll("_", " ")} · {invitation.delivery_status} · {formatKuwaitDateTime(invitation.expires_at, result.context.profile.locale)}</p><p className="text-sm">{invitation.accepted_at ? "accepted" : invitation.revoked_at ? "revoked" : new Date(invitation.expires_at) <= new Date() ? "expired" : "pending"}</p></div><div className="flex flex-wrap gap-2">{!invitation.accepted_at && !invitation.revoked_at ? <><form action={resendInvitation}><input type="hidden" name="invitationId" value={invitation.id} /><button className="rounded-lg border border-border px-3 py-2 text-sm font-medium">{messages["team.resend"]}</button></form><form action={revokeInvitation}><input type="hidden" name="invitationId" value={invitation.id} /><button className="rounded-lg border border-red-200 px-3 py-2 text-sm font-medium text-red-700">{messages["team.revoke"]}</button></form></> : null}</div></article>)}{result.invitations.length === 0 ? <p className="rounded-xl border border-dashed border-border p-6 text-muted">{messages["common.empty"]}</p> : null}</section>
  </div>;
}
