import Link from "next/link";

import { AccessibleBarChart } from "@/components/analytics/bar-chart";
import { MetricCard } from "@/components/analytics/metric-card";
import { getSurveyAnalytics } from "@/features/analytics/server";
import { formatKuwaitDateTime } from "@/lib/datetime/kuwait";

export default async function SurveyAnalyticsPage({ params, searchParams }: { params: Promise<{ surveyId: string }>; searchParams: Promise<Record<string, string | undefined>> }) {
  const [{ surveyId }, raw] = await Promise.all([params, searchParams]);
  const result = await getSurveyAnalytics(surveyId, raw);
  return <div className="grid gap-7"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-brand">Question analytics</p><h1 className="mt-2 text-3xl font-bold">{result.survey.title_en}</h1><p className="mt-2 text-muted">{result.range.from} – {result.range.to} · {result.survey.status}</p></div><Link className="rounded-xl border border-border bg-white px-4 py-2 font-semibold" href={`/dashboard/surveys/${surveyId}`}>Survey details</Link></header>
    <form className="flex flex-wrap gap-3 rounded-2xl border border-border bg-white p-4"><label className="grid gap-1 text-xs font-semibold">Date range<select className="rounded-xl border border-border px-3 py-2" name="preset" defaultValue={raw.preset ?? "30d"}><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option><option value="this_month">This month</option><option value="previous_month">Previous month</option></select></label><button className="self-end rounded-xl bg-brand px-4 py-2.5 font-bold text-white">Apply</button></form>
    {result.questions.map((question) => <section key={question.id} className="grid gap-5 rounded-3xl border border-border bg-white p-6"><div><p className="text-xs font-bold uppercase tracking-wide text-brand">{question.type.replace("_", " ")}</p><h2 className="mt-1 text-xl font-bold">{question.label_en}</h2><p className="text-sm text-muted" dir="rtl">{question.label_ar}</p></div><MetricCard label="Responses" value={String(question.response_count)} />
      {question.rating ? <div className="grid gap-5 md:grid-cols-[14rem_1fr]"><div className="grid gap-3"><MetricCard label="Average" value={question.rating.average === null ? "No data" : `${question.rating.average} / ${question.rating.max}`} /><MetricCard label="Median" value={question.rating.median === null ? "No data" : String(question.rating.median)} /></div><AccessibleBarChart title={`${question.label_en} rating distribution`} items={question.rating.distribution.map((item) => ({ label: String(item.value), value: item.count }))} /></div> : null}
      {question.options ? <AccessibleBarChart title={`${question.label_en} option distribution`} suffix="%" items={question.options.map((option) => ({ label: `${option.label_en} · ${option.label_ar}`, value: option.percentage, detail: `${option.count} selections` }))} /> : null}
      {question.recent_text_answers ? <div><h3 className="font-bold">Recent answers</h3><div className="mt-3 grid gap-3">{question.recent_text_answers.map((answer) => <article key={`${answer.response_id}-${answer.submitted_at}`} className="rounded-xl bg-background p-4"><p className="whitespace-pre-wrap break-words">{answer.text}</p><p className="mt-2 text-xs text-muted">{formatKuwaitDateTime(answer.submitted_at)}</p></article>)}</div>{question.recent_text_answers.length === 0 ? <p className="mt-3 text-sm text-muted">No text answers in this period.</p> : null}</div> : null}
    </section>)}
    {result.questions.some((question) => question.recent_text_answers !== null) ? <nav aria-label="Text answer pages" className="flex justify-center gap-3"><Link className={`rounded-xl border border-border px-4 py-2 ${result.textPage === 1 ? "pointer-events-none opacity-50" : ""}`} aria-disabled={result.textPage === 1} href={{ pathname: `/dashboard/surveys/${surveyId}/analytics`, query: { ...raw, textPage: Math.max(1, result.textPage - 1) } }}>Previous answers</Link><span className="px-2 py-2 text-sm text-muted">Page {result.textPage}</span><Link className={`rounded-xl border border-border px-4 py-2 ${result.questions.some((question) => question.recent_text_answers?.length === result.textPageSize) ? "" : "pointer-events-none opacity-50"}`} aria-disabled={!result.questions.some((question) => question.recent_text_answers?.length === result.textPageSize)} href={{ pathname: `/dashboard/surveys/${surveyId}/analytics`, query: { ...raw, textPage: result.textPage + 1 } }}>Next answers</Link></nav> : null}
  </div>;
}
