import { saveLocation } from "@/features/settings/actions";
import { getMessages, type Locale } from "@/lib/i18n/messages";

type LocationValue = { id?: string; slug?: string; name_en?: string; name_ar?: string; governorate?: string; area?: string; address_en?: string | null; address_ar?: string | null; phone?: string | null; email?: string | null; opening_hours?: unknown; inherits_timezone?: boolean; timezone?: string; status?: string };

export function LocationForm({ organizationId, locale, location = {} }: { organizationId: string; locale: Locale; location?: LocationValue }) {
  const m = getMessages(locale); const input = "rounded-xl border border-border px-3 py-2";
  return <form action={saveLocation} className="grid gap-4 rounded-3xl border border-border bg-white p-6 md:grid-cols-2"><input type="hidden" name="organizationId" value={organizationId} />{location.id ? <input type="hidden" name="locationId" value={location.id} /> : null}<label className="grid gap-2 font-semibold">Slug<input required name="slug" defaultValue={location.slug ?? ""} className={input} /></label><label className="grid gap-2 font-semibold">{m["settings.nameEn"]}<input required name="nameEn" defaultValue={location.name_en ?? ""} className={input} /></label><label className="grid gap-2 font-semibold">{m["settings.nameAr"]}<input name="nameAr" dir="rtl" defaultValue={location.name_ar ?? ""} className={input} /></label><label className="grid gap-2 font-semibold">{m["location.governorate"]}<select name="governorate" defaultValue={location.governorate ?? "capital"} className={input}>{["capital","hawalli","farwaniya","mubarak_al_kabeer","ahmadi","jahra"].map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label><label className="grid gap-2 font-semibold">{m["location.area"]}<input required name="area" defaultValue={location.area ?? ""} className={input} /></label><label className="grid gap-2 font-semibold">{m["settings.phone"]}<input name="phone" defaultValue={location.phone ?? ""} className={input} /></label><label className="grid gap-2 font-semibold">{m["auth.email"]}<input type="email" name="email" defaultValue={location.email ?? ""} className={input} /></label><label className="grid gap-2 font-semibold">Address (English)<textarea name="addressEn" defaultValue={location.address_en ?? ""} className={`${input} min-h-24`} /></label><label className="grid gap-2 font-semibold">العنوان بالعربية<textarea name="addressAr" dir="rtl" defaultValue={location.address_ar ?? ""} className={`${input} min-h-24`} /></label><label className="grid gap-2 font-semibold md:col-span-2">{m["location.openingHours"]} (JSON)<textarea name="openingHours" defaultValue={JSON.stringify(location.opening_hours ?? {}, null, 2)} className={`${input} min-h-32 font-mono text-sm`} /></label><label className="flex items-center gap-2"><input type="checkbox" name="inheritsTimezone" defaultChecked={location.inherits_timezone ?? true} /> Inherit organization timezone</label><input type="hidden" name="timezone" value="Asia/Kuwait" /><label className="grid gap-2 font-semibold">{m["team.status"]}<select name="status" defaultValue={location.status ?? "active"} className={input}><option value="active">{m["location.active"]}</option><option value="archived">{m["location.inactive"]}</option></select></label><button className="justify-self-start rounded-xl bg-brand px-5 py-3 font-bold text-white">{m["common.save"]}</button></form>;
}
