"use client";

import Image from "next/image";
import { useEffect, useState } from "react";

export default function KioskSetupPage() {
  const [token, setToken] = useState<string | null>(null); const [status, setStatus] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { const value = new URLSearchParams(window.location.search).get("token"); window.history.replaceState({}, "", "/kiosk/setup"); queueMicrotask(() => setToken(value)); if (value) void fetch("/api/kiosk/setup/opened", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token: value }) }); }, []);
  async function enroll() { if (!token) return; setBusy(true); setStatus(null); try { const r = await fetch("/api/kiosk/enroll", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token }) }); if (!r.ok) throw new Error(); const data = await r.json() as { redirectTo: string }; window.location.assign(data.redirectTo); } catch { setStatus("This setup link is invalid, expired, or has already been used. Ask an administrator for a new link."); } finally { setBusy(false); } }
  return <main className="min-h-dvh bg-slate-950 px-5 py-10 text-white"><section className="mx-auto flex min-h-[calc(100dvh-5rem)] max-w-lg flex-col justify-center"><Image src="/brand/review-and-more-logo-on-dark.png" alt="Review and More" width={190} height={40} className="mb-10 h-auto w-auto" priority /><h1 className="text-3xl font-bold">Set up this kiosk</h1><p className="mt-4 text-slate-300">Use the button below to securely enroll this iPad. Do not share this device while setup is in progress.</p>{!token && <p role="alert" className="mt-5 rounded-lg bg-amber-950 p-4 text-amber-100">This page needs a setup link. Ask an administrator to scan a new QR code.</p>}{status && <p role="alert" aria-live="polite" className="mt-5 rounded-lg bg-red-950 p-4 text-red-100">{status}</p>}<button disabled={!token || busy} onClick={() => void enroll()} className="mt-8 min-h-12 w-full rounded-xl bg-white px-5 text-base font-bold text-slate-950 disabled:opacity-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white">{busy ? "Setting up…" : "Set up this device"}</button><p className="mt-5 text-sm text-slate-400">Setup only starts after you select the button.</p></section></main>;
}